#!/bin/bash

OUTPUT_DIR="output"
BUILD_TARGET_FILE=$1
OUTPUT_FILE_NAME="${BUILD_TARGET_FILE%.*}"

GCC_OPTION="-Wall"

echo $BUILD_TARGET_FILE
echo $OUTPUT_DIR/$OUTPUT_FILE_NAME
echo "option $GCC_OPTION"

g++ -o $OUTPUT_DIR/$OUTPUT_FILE_NAME $GCC_OPTION $BUILD_TARGET_FILE